name: Example Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Scheduled to run daily at midnight

jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.access }}

    # Example step to run your Python script
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML requests Flask SQLAlchemy

    - name: Run Python Script
      run: python python RTO.py
      env:
        SECRET_KEY: ${{ secrets.ACCESS }}

        

